@api = http://localhost:3000/projects

GET {{api}}

###
GET {{api}}/1

###
POST {{api}}
Content-Type: application/json

{
    "project_name": "Here is another project",
    "project_description": "Empty project"
}

###
DELETE {{api}}/8

###
PUT {{api}}/1
Content-Type: application/json

{
    "project_name": "An updated Title",
    "project_description": "An updated Description"
}